/*
 * This file is autogenerated.
 */
package org.anarres.ipmi.protocol.client.visitor;

import javax.annotation.Nonnull;
import org.anarres.ipmi.protocol.packet.asf.AsfRmcpData;
import org.anarres.ipmi.protocol.packet.asf.AsfResetData;
import org.anarres.ipmi.protocol.packet.asf.AsfPowerUpData;
import org.anarres.ipmi.protocol.packet.asf.AsfUnconditionalPowerDownData;
import org.anarres.ipmi.protocol.packet.asf.AsfPowerCycleResetData;
import org.anarres.ipmi.protocol.packet.asf.AsfPresencePongData;
import org.anarres.ipmi.protocol.packet.asf.AsfCapabilitiesResponseData;
import org.anarres.ipmi.protocol.packet.asf.AsfSystemStateResponseData;
import org.anarres.ipmi.protocol.packet.asf.AsfOpenSessionResponseData;
import org.anarres.ipmi.protocol.packet.asf.AsfCloseSessionResponseData;
import org.anarres.ipmi.protocol.packet.asf.AsfPresencePingData;
import org.anarres.ipmi.protocol.packet.asf.AsfCapabilitiesRequestData;
import org.anarres.ipmi.protocol.packet.asf.AsfSystemStateRequestData;
import org.anarres.ipmi.protocol.packet.asf.AsfOpenSessionRequestData;
import org.anarres.ipmi.protocol.packet.asf.AsfCloseSessionRequestData;
import org.anarres.ipmi.protocol.packet.asf.AsfRAKPMessage1Data;
import org.anarres.ipmi.protocol.packet.asf.AsfRAKPMessage2Data;
import org.anarres.ipmi.protocol.packet.asf.AsfRAKPMessage3Data;

/**
 * Autogenerated visitor handler for {@link AsfRmcpData} subclasses.
 *
 * @author shevek
 */
public interface IpmiClientAsfMessageHandler {

    public static class Adapter implements IpmiClientAsfMessageHandler {

        public void handleDefault(@Nonnull AsfRmcpData message) {
        }

        @Override
        public void handleAsfResetData(AsfResetData message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfPowerUpData(AsfPowerUpData message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfUnconditionalPowerDownData(AsfUnconditionalPowerDownData message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfPowerCycleResetData(AsfPowerCycleResetData message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfPresencePongData(AsfPresencePongData message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfCapabilitiesResponseData(AsfCapabilitiesResponseData message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfSystemStateResponseData(AsfSystemStateResponseData message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfOpenSessionResponseData(AsfOpenSessionResponseData message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfCloseSessionResponseData(AsfCloseSessionResponseData message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfPresencePingData(AsfPresencePingData message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfCapabilitiesRequestData(AsfCapabilitiesRequestData message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfSystemStateRequestData(AsfSystemStateRequestData message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfOpenSessionRequestData(AsfOpenSessionRequestData message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfCloseSessionRequestData(AsfCloseSessionRequestData message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfRAKPMessage1Data(AsfRAKPMessage1Data message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfRAKPMessage2Data(AsfRAKPMessage2Data message) {
            handleDefault(message);
        }

        @Override
        public void handleAsfRAKPMessage3Data(AsfRAKPMessage3Data message) {
            handleDefault(message);
        }
    }

    public void handleAsfResetData(@Nonnull AsfResetData message);

    public void handleAsfPowerUpData(@Nonnull AsfPowerUpData message);

    public void handleAsfUnconditionalPowerDownData(@Nonnull AsfUnconditionalPowerDownData message);

    public void handleAsfPowerCycleResetData(@Nonnull AsfPowerCycleResetData message);

    public void handleAsfPresencePongData(@Nonnull AsfPresencePongData message);

    public void handleAsfCapabilitiesResponseData(@Nonnull AsfCapabilitiesResponseData message);

    public void handleAsfSystemStateResponseData(@Nonnull AsfSystemStateResponseData message);

    public void handleAsfOpenSessionResponseData(@Nonnull AsfOpenSessionResponseData message);

    public void handleAsfCloseSessionResponseData(@Nonnull AsfCloseSessionResponseData message);

    public void handleAsfPresencePingData(@Nonnull AsfPresencePingData message);

    public void handleAsfCapabilitiesRequestData(@Nonnull AsfCapabilitiesRequestData message);

    public void handleAsfSystemStateRequestData(@Nonnull AsfSystemStateRequestData message);

    public void handleAsfOpenSessionRequestData(@Nonnull AsfOpenSessionRequestData message);

    public void handleAsfCloseSessionRequestData(@Nonnull AsfCloseSessionRequestData message);

    public void handleAsfRAKPMessage1Data(@Nonnull AsfRAKPMessage1Data message);

    public void handleAsfRAKPMessage2Data(@Nonnull AsfRAKPMessage2Data message);

    public void handleAsfRAKPMessage3Data(@Nonnull AsfRAKPMessage3Data message);
}
