/*
 * This file is autogenerated.
 */
package org.anarres.ipmi.protocol.client.visitor;

import javax.annotation.Nonnull;
import org.anarres.ipmi.protocol.packet.asf.AsfRmcpData;
import org.anarres.ipmi.protocol.packet.asf.AsfResetData;
import org.anarres.ipmi.protocol.packet.asf.AsfPowerUpData;
import org.anarres.ipmi.protocol.packet.asf.AsfUnconditionalPowerDownData;
import org.anarres.ipmi.protocol.packet.asf.AsfPowerCycleResetData;
import org.anarres.ipmi.protocol.packet.asf.AsfPresencePongData;
import org.anarres.ipmi.protocol.packet.asf.AsfCapabilitiesResponseData;
import org.anarres.ipmi.protocol.packet.asf.AsfSystemStateResponseData;
import org.anarres.ipmi.protocol.packet.asf.AsfOpenSessionResponseData;
import org.anarres.ipmi.protocol.packet.asf.AsfCloseSessionResponseData;
import org.anarres.ipmi.protocol.packet.asf.AsfPresencePingData;
import org.anarres.ipmi.protocol.packet.asf.AsfCapabilitiesRequestData;
import org.anarres.ipmi.protocol.packet.asf.AsfSystemStateRequestData;
import org.anarres.ipmi.protocol.packet.asf.AsfOpenSessionRequestData;
import org.anarres.ipmi.protocol.packet.asf.AsfCloseSessionRequestData;
import org.anarres.ipmi.protocol.packet.asf.AsfRAKPMessage1Data;
import org.anarres.ipmi.protocol.packet.asf.AsfRAKPMessage2Data;
import org.anarres.ipmi.protocol.packet.asf.AsfRAKPMessage3Data;

/**
 * Autogenerated visitor handler for {@link AsfRmcpData} subclasses.
 *
 * @author shevek
 */
public interface IpmiClientAsfMessageHandler {

    public static class Adapter implements IpmiClientAsfMessageHandler {

        public void handleDefault(@Nonnull IpmiHandlerContext context, @Nonnull AsfRmcpData message) {
        }

        @Override
        public void handleAsfResetData(IpmiHandlerContext context, AsfResetData message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfPowerUpData(IpmiHandlerContext context, AsfPowerUpData message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfUnconditionalPowerDownData(IpmiHandlerContext context, AsfUnconditionalPowerDownData message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfPowerCycleResetData(IpmiHandlerContext context, AsfPowerCycleResetData message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfPresencePongData(IpmiHandlerContext context, AsfPresencePongData message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfCapabilitiesResponseData(IpmiHandlerContext context, AsfCapabilitiesResponseData message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfSystemStateResponseData(IpmiHandlerContext context, AsfSystemStateResponseData message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfOpenSessionResponseData(IpmiHandlerContext context, AsfOpenSessionResponseData message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfCloseSessionResponseData(IpmiHandlerContext context, AsfCloseSessionResponseData message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfPresencePingData(IpmiHandlerContext context, AsfPresencePingData message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfCapabilitiesRequestData(IpmiHandlerContext context, AsfCapabilitiesRequestData message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfSystemStateRequestData(IpmiHandlerContext context, AsfSystemStateRequestData message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfOpenSessionRequestData(IpmiHandlerContext context, AsfOpenSessionRequestData message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfCloseSessionRequestData(IpmiHandlerContext context, AsfCloseSessionRequestData message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfRAKPMessage1Data(IpmiHandlerContext context, AsfRAKPMessage1Data message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfRAKPMessage2Data(IpmiHandlerContext context, AsfRAKPMessage2Data message) {
            handleDefault(context, message);
        }

        @Override
        public void handleAsfRAKPMessage3Data(IpmiHandlerContext context, AsfRAKPMessage3Data message) {
            handleDefault(context, message);
        }
    }

    public void handleAsfResetData(@Nonnull IpmiHandlerContext context, @Nonnull AsfResetData message);

    public void handleAsfPowerUpData(@Nonnull IpmiHandlerContext context, @Nonnull AsfPowerUpData message);

    public void handleAsfUnconditionalPowerDownData(@Nonnull IpmiHandlerContext context, @Nonnull AsfUnconditionalPowerDownData message);

    public void handleAsfPowerCycleResetData(@Nonnull IpmiHandlerContext context, @Nonnull AsfPowerCycleResetData message);

    public void handleAsfPresencePongData(@Nonnull IpmiHandlerContext context, @Nonnull AsfPresencePongData message);

    public void handleAsfCapabilitiesResponseData(@Nonnull IpmiHandlerContext context, @Nonnull AsfCapabilitiesResponseData message);

    public void handleAsfSystemStateResponseData(@Nonnull IpmiHandlerContext context, @Nonnull AsfSystemStateResponseData message);

    public void handleAsfOpenSessionResponseData(@Nonnull IpmiHandlerContext context, @Nonnull AsfOpenSessionResponseData message);

    public void handleAsfCloseSessionResponseData(@Nonnull IpmiHandlerContext context, @Nonnull AsfCloseSessionResponseData message);

    public void handleAsfPresencePingData(@Nonnull IpmiHandlerContext context, @Nonnull AsfPresencePingData message);

    public void handleAsfCapabilitiesRequestData(@Nonnull IpmiHandlerContext context, @Nonnull AsfCapabilitiesRequestData message);

    public void handleAsfSystemStateRequestData(@Nonnull IpmiHandlerContext context, @Nonnull AsfSystemStateRequestData message);

    public void handleAsfOpenSessionRequestData(@Nonnull IpmiHandlerContext context, @Nonnull AsfOpenSessionRequestData message);

    public void handleAsfCloseSessionRequestData(@Nonnull IpmiHandlerContext context, @Nonnull AsfCloseSessionRequestData message);

    public void handleAsfRAKPMessage1Data(@Nonnull IpmiHandlerContext context, @Nonnull AsfRAKPMessage1Data message);

    public void handleAsfRAKPMessage2Data(@Nonnull IpmiHandlerContext context, @Nonnull AsfRAKPMessage2Data message);

    public void handleAsfRAKPMessage3Data(@Nonnull IpmiHandlerContext context, @Nonnull AsfRAKPMessage3Data message);
}
